# ./conda.yml
name: nyc_airbnb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - autopep8=1.5.7
  - click=8.0.3
  - oss2=2.15.0
  - numpy=1.21.2
  - pandas=1.3.3
  - coverage=6.0
  - python-dotenv=0.19.0
  - hydra-core=1.0.6
  - pip=21.2.4
  - python-decouple
  - pyarrow=6.0.1
  - scikit-learn=0.24.1
  - scipy=1.7.3
  - tqdm=4.62.3
  - imbalanced-learn=0.8.1
  - wandb=0.12.1
  - pytorch=1.10.0
  - mlflow=1.20.2
  - pip:
      - fsspec==2021.11.0