main:
  project_name: "nyc_airbnb"
  experiment_name: "random_forest_model"
  steps: all
data:
  bucket: "junda-mlops"
  object: "dataset/training_data/"
  raw_data: "raw_training_data.parquet"
  training_data: "trainval_data.parquet"
  test_data: "test_data.parquet"
  label: "price"
modeling:
  # Name of exported model to be used in testing model
  test_model: "random_forest_model:latest"
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.2
  # Fraction of remaining data to use for validation
  val_size: 0.2
  # Fix this for reproducibility, change to have new splits
  random_seed: 42
  # Column to use for stratification (use "none" for no stratification)
  stratify_by: "none"
  max_tfidf_features: 15
  # NOTE: you can put here any parameter that is accepted by the constructor of
  # RandomForestRegressor. This is a subsample, but more could be added:
  random_forest:
    n_estimators: 100
    max_depth: 12
    min_samples_split: 4
    min_samples_leaf: 3
    # Here -1 means all available cores
    n_jobs: -1
    criterion: mae
    max_features: 0.5
    # DO not change the following
    oob_score: true
