wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1659774865
    t:
      4: 3.8.12
      5: 0.12.1
      8:
      - 5
bucket:
  desc: null
  value: junda-mlops
object-path:
  desc: null
  value: dataset/training_data/
